# Generated by Django 5.1.7 on 2025-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='dose_intervals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
