# Generated by Django 5.1.7 on 2025-03-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_vaccine_dose_intervals_vaccine_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationschedule',
            name='vaccine',
        ),
    ]
