# Generated by Django 5.1.7 on 2025-03-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_remove_vaccinationschedule_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationschedule',
            name='vaccine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccine'),
            preserve_default=False,
        ),
    ]
