# Generated by Django 5.1.7 on 2025-03-11 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0004_vaccinationschedule_vaccine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vaccinationschedule',
            name='date',
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='dose_dates',
            field=models.JSONField(default=list),
        ),
    ]
