# Generated by Django 5.1.7 on 2025-03-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0005_remove_vaccinationschedule_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='doses_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dose_intervals',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
