# Generated by Django 5.1.7 on 2025-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0006_vaccine_doses_required_alter_vaccine_dose_intervals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='dose_intervals',
            field=models.JSONField(default=list),
        ),
    ]
