# Generated by Django 5.1.7 on 2025-03-12 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0008_vaccinecampaign_vaccinationschedule_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinecampaign'),
        ),
    ]
