# Generated by Django 5.1.7 on 2025-03-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0009_alter_vaccinationschedule_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationschedule',
            name='dose_dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
