# Generated by Django 5.1.7 on 2025-04-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0011_vaccinationschedule_payment_method_vaccine_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='stock',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
