# Generated by Django 5.1.7 on 2025-04-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0013_vaccineimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaign',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
