# Generated by Django 5.1.7 on 2025-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0015_alter_vaccine_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='dose_intervals',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='doses_required',
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
