# Generated by Django 5.1.7 on 2025-05-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0016_remove_vaccine_dose_intervals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
